sudo: required
language: generic
services:
  - docker 
before_install: 
  - docker build -t rkulkarni/docker-react-sample -f Dockerfile.dev .

script:
  - docker run -e CI=true rkulkarni/docker-react-sample npm run test -- --coverage